const destinationsArray = [
  {
    name: "Mars",
    avgDistanceInKm: 2.25e+8,
    travelTimeInHrs: 33,
    priceInUSD: 5e+4,
    ships: "/imgs/valkyrie.png",
    lengthOfDayInHrs: 24.6,
    radiusInKm: 3389,
    gravity: "3.71 m/s²",
    escapeVelocity: "11.2 km/s",
    massInKg: 6.39e+23,
    density: "3.93 g/cm³",
    image: "/imgs/mars.png"
  },{
    name: "Venus",
    avgDistanceInKm: 2.61e+8,
    travelTimeInHrs: 34.8,
    priceInUSD: 7e+4,
    ships: '/imgs/galileo.png',
    lengthOfDayInHrs: 2802,
    radiusInKm: 6052,
    gravity: "8.87 m/s²",
    escapeVelocity: "10.36 km/s",
    massInKg: 4.87e+24,
    density: "5.24 g/cm³",
    image: '/imgs/venus.png'
  },{
    name: "Europa",
    avgDistanceInKm: 6.28e+8,
    travelTimeInHrs: 92.3,
    priceInUSD: 14e+4,
    ships: "/imgs/valkyrie.png",
    lengthOfDayInHrs: 85,
    radiusInKm: 1561,
    gravity: "1.315 m/s²",
    escapeVelocity: "2.025 km/s",
    massInKg: 4.8e+22,
    density: "3.01 g/cm³",
    image: "/imgs/europa.png"  
  }, {
    name: "Jupiter",
    avgDistanceInKm: 5.88e+8,
    travelTimeInHrs: 86.5,
    priceInUSD: 12e+4,
    ships: "/imgs/valkyrie.png",
    lengthOfDayInHrs: 9.9,
    radiusInKm: 69911,
    gravity: "24.79 m/s²",
    escapeVelocity: "59.5 km/s",
    massInKg: 1.89e+27,
    density: "1.33 g/cm³",
    image: "/imgs/jupiter.png"
  }, {
    name: "Saturn",
    avgDistanceInKm: 1.2e+9,
    travelTimeInHrs: 160,
    priceInUSD: 21e+4,
    ships: '/imgs/galileo.png',
    lengthOfDayInHrs: 10.7,
    radiusInKm: 58232,
    gravity: "10.44 m/s²",
    escapeVelocity: "35.5 km/s",
    massInKg: 5.68e+26,
    density: "0.687 g/cm³",
    image: "/imgs/saturn.png"
  },{
    name: "Bezos Elite VIP Spaceclub",
    avgDistanceInKm: "7.5e+9",
    travelTimeInHrs: "75",
    priceInUSD: "5.274e+7",
    ships: '/imgs/osiris.png',
    lengthOfDayInHrs: "24",
    radiusInKm: "3",
    gravity: "9.8 m/s²",
    escapeVelocity: "N/A",
    massInKg: "4.8e+18",
    density: "N/A",
    image: "/imgs/spacestation.png"
  }, {
    name: "Ganymede",
    avgDistanceInKm: 6.3e+8,
    travelTimeInHrs: 84,
    priceInUSD:1e+5,
    ships: '/imgs/galileo.png',
    lengthOfDayInHrs: 168,
    radiusInKm: 2634,
    gravity: "1.428 m/s²",
    escapeVelocity: "2.734 km/s",
    massInKg: 1.48e+23,
    density: "1.94 g/cm³",
    image: "/imgs/ganymede.png"
  }, {
    name: "Neptune",
    avgDistanceInKm: "4.3e+9",
    travelTimeInHrs: "43",
    priceInUSD: "1e+6",
    ships: '/imgs/osiris.png',
    lengthOfDayInHrs: "16",
    radiusInKm: "24622",
    gravity: "11.15 m/s²",
    escapeVelocity: "23.5 km/s",
    massInKg: "1.02e+26",
    density: "1.02 g/m³",
    image: "/imgs/neptune.png"
  }, {
    name: "Callisto",
    avgDistanceInKm: 6.28e+8,
    travelTimeInHrs: 6.3,
    priceInUSD: 1e+5,
    ships: '/imgs/osiris.png',
    lengthOfDayInHrs: 400.8,
    radiusInKm: 2410,
    gravity: "1.236 m/s²",
    escapeVelocity: "2.44 km/s",
    massInKg: 1.08e+23,
    density: "1.64 g/cm³ ",
    image: "/imgs/callisto.png"
  },{
    name: "Earth",
    avgDistanceInKm: 0,
    travelTimeInHrs: 0,
    priceInUSD: 0,
    ships: "/imgs/galileo.png",
    lengthOfDayInHrs: 24,
    radiusInKm: 6371,
    gravity: "9.8 m/s²",
    escapeVelocity: '11.2 km/s',
    massInKg: 5.972e+24,
    density: "5.51 g/cm³",
    image: "/imgs/earth.png"
  }
]
module.exports = destinationsArray;

// Nice work for your seed data, however, you would probably want to seperate this file into a seperate directory.